[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.package_name }}"
version = "0.1.0"
dependencies = []

[tool.setuptools]
packages = ["{{ cookiecutter.package_name }}"]
